export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";


export const EDITED_SUCCESS = "EDITED_SUCCESS";
export const EDITED_ERROR = "EDITED_ERROR";
export const FETCHING_PROFILE_DETAILS_SUCCESS = "FETCHING_PROFILE_DETAILS_SUCCESS"
export const FETCHING_PROFILE_DETAILS_ERROR = "FETCHING_PROFILE_DETAILS_ERROR"


export const LOADING_MOVIES_SUCCESS = "LOADING_MOVIES_SUCCESS";
export const LOADING_MOVIES_ERROR = "LOADING_MOVIES_ERROR";
export const MOVIE_LOADING_DONE = "MOVIE_LOADING_DONE";

export const AUTHENTICATED = "AUTHENTICATED";
export const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";

export const FETCHING_CP_USERS_SUCCESS  = "FETCHING_CP_USERS_SUCCESS";
export const FETCHING_CP_USERS_FAIL = "FETCHING_CP_USERS_FAIL";

export const FETCHING_ALL_USERS_SUCCESS  = "FETCHING_ALL_USERS_SUCCESS";
export const FETCHING_ALL_USERS_FAIL = "FETCHING_ALL_USERS_FAIL";


export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_FAIL = "BLOCK_USER_FAIL";

export const LOGIN_CPUSER_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_CPUSER_ERROR = "LOGIN_ERROR";
export const REGISTRATING_CPUSER_SUCCESS = "REGISTRATING_CPUSER_SUCCESS"
export const REGISTRATING_CPUSER_FAIL = "REGISTRATING_CPUSER_FAIL"